version: 2.1

executors:
  vm:
    machine:
      enabled: true
      image: circleci/classic:latest

jobs:
  build:
    executor: vm
    shell: /bin/bash --login -eo pipefail 
    steps:
    - run: lsb_release -a
    - run:
        name: Installing development tools
        command: sudo apt-get install build-essential
    - run:
        name: Installing Brew
        command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    - run:
        name: Add brew to the PATH
        command: |
          echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> ~/.bash_profile
    - run:
        name: Installing qemu
        no_output_timeout: 60m
        command: sudo apt-get install qemu
    - run:
        name: Installing packer
        no_output_timeout: 60m
        command: brew install packer
    - run: pwd
    - run: ls -alFh
    - run: ls -alFhR ~
    - run:
        name: Building Image
        command: rake packer:build:qemu-alpine-image
