version: 2.1

executors:
  vm:
    machine:
      enabled: true
      image: circleci/classic:latest

jobs:
  build:
    executor: vm
    steps:
    - run : sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
                
