version: 2.1

executors:
  vm:
    machine:
      enabled: true
      image: circleci/classic:latest

jobs:
  build:
    executor: vm
    shell: /bin/bash --login -eo pipefail
    envionment:
      DKR: https://github.com/jupytercloud-project/build-container/releases/download/0.0.1/jupytercloud-project_build-container_latest.dkr
    steps:
    - checkout
    - run:
        name: Pulling build container
        command: curl --location ${DKR} | docker load
    - run:
        name: Running build container
        command: docker run -it jupytercloud-project/build-container:latest
