version: 2.1

executors:
  vm:
    machine:
      enabled: true
      image: circleci/classic:latest

jobs:
  build:
    executor: vm
    steps:
    - run:
        name: Install dev tools
        command: sudo apt-get install build-essential
    - run:
        name: Install Brew
        command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    - run:
        name: Add brew to the PATH
        command: |
          echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> ~/.bash_profile
    - run:
        name: Install tools
        shell: /bin/bash --login -eo pipefail 
        command: brew install gcc packer qemu
