version: 2.1

executors:
  vm:
    machine:
      enabled: true
      image: circleci/classic:latest

jobs:
  build:
    executor: vm
    steps:
    - run : sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    - run : sudo apt-get install build-essential
    - run : echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >>~/.profile
    - run : eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    - run : echo $PATH
    - run : pwd
    - run : ls -alFh
    - run : brew install gcc packer qemu
