version: 2.1

executors:
  vm:
    machine:
      enabled: true
      image: circleci/classic:latest

jobs:
  build:
    executor: vm
    steps:
    - run:
        name: Install dev tools
        command: sudo apt-get install build-essential
    - run:
        name: Install LinuxBrew
        command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    - run:
        name: Add brew to the PATH
        command: |
          echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> $BASH_ENV
    - run: echo $PATH
    - run: pwd
    - run: ls -alFh ~
    - run: brew install gcc packer qemu
