version: 2.1

executors:
  vm:
    machine:
      enabled: true
      image: circleci/classic:latest

jobs:
  build:
    executor: vm
    shell: /bin/bash --login -eo pipefail
    environment:
      ARTIFACT_DIR: ./qemu-registry
      GHR: github.com/tcnksm/ghr
    steps:
    - checkout
    - attach_workspace:
        at: ./qemu-registry
    - run:
        name: "Define environment variables"
        command: |
          echo 'export RELEASE_VERSION=0.0.1' >> ${BASH_ENV}
    - run:
        name: "Running build container"
        command: |
          docker-compose up
    - run:
        name: "Publishing release on GitHub"
        command: |
          go get ${GHR} && \
          VERSION=${RELEASE_VERSION} \
          ghr -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -delete \
              ${RELEASE_VERSION} \
              ${ARTIFACT_DIR}/
